# Generated by Django 4.2.5 on 2023-09-09 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.keywords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hasSeen', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.articles')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.keywords')),
            ],
        ),
    ]
