import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'zh_Hans', 'hi', 'ar', 'es', 'de'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? zh_HansText = '',
    String? hiText = '',
    String? arText = '',
    String? esText = '',
    String? deText = '',
  }) =>
      [enText, zh_HansText, hiText, arText, esText, deText][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Login
  {
    'n4aa6mpw': {
      'en': 'Welcome Back!',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '220rw64q': {
      'en': 'Use the form below to access your account.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '5z6zyepw': {
      'en': 'Email Address',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'g5dozcpq': {
      'en': 'Enter your email here...',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'bgurx6c2': {
      'en': 'Password',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'e9gvphlt': {
      'en': 'Enter your password here...',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'wfid548q': {
      'en': 'Forgot Password?',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '1c54coej': {
      'en': 'Login',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '2lu04zuu': {
      'en': 'Use a social platform to continue',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '06tedx9h': {
      'en': 'Don\'t have an account?',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'ymo82ml7': {
      'en': 'Create Account',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '11555rjp': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // createAccount
  {
    'x8in438g': {
      'en': 'Get Started',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'sn5kh1vb': {
      'en': 'Use the form below to get started.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'mcu284qu': {
      'en': 'Email Address',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'pbrefa7y': {
      'en': 'Enter your email here...',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '86j22054': {
      'en': 'Password',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '42ba9zo2': {
      'en': 'Enter your password here...',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'dsbeccci': {
      'en': 'Confirm Password',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'cgc5nhnw': {
      'en': 'Re-enter your password here...',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '2utoo6l5': {
      'en': 'Create Account',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '5qldiow8': {
      'en': 'Use a social platform to continue',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '17b54gab': {
      'en': 'Already have an account?',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'rdew77wx': {
      'en': 'Log In',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'db3ozn7u': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // Routing
  {
    '430gjb2n': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // forgotPassword
  {
    '2layu0b0': {
      'en': 'Reset Password',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'dl8ecxv9': {
      'en':
          'Don\'t remember your password? Enter the email associated with your account below and we will send you a new link.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'sf3dw8i4': {
      'en': 'Email Address',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'vrchg8qs': {
      'en': 'Enter your email here...',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '2zeykfcy': {
      'en': 'Send Reset Link',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '4jgafnfs': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // Dashboard
  {
    'ob39qriy': {
      'en': 'Dashboard',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '11bw5d39': {
      'en': 'Search companies...',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '1t6tr01u': {
      'en': 'Quantum Computing Advance Begins New Era, IBM Says',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '4jwxrrpe': {
      'en':
          'A quantum computer came up with better answers to a physics problem than a conventional supercomputer.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'fzd4bg9v': {
      'en': 'Your Research Articles',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'kjvtm987': {
      'en': 'Super diffusion on a quantum computer',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'k8igura9': {
      'en':
          'Trinity\'s quantum physicists in collaboration with IBM Dublin have successfully simulated super diffusion in a system of interacting quantum particles on a quantum computer.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'ydhjk5fx': {
      'en': 'Dashboard',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '09m2bdke': {
      'en': '__',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // Articles
  {
    'bb6fyzar': {
      'en': 'Research Articles',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'glnb3lnq': {
      'en': 'Search library...',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'gwvsoh12': {
      'en': 'Latest',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'i7at9yxy': {
      'en': 'Quantum Computing Advance Begins New Era, IBM Says',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'p2udrmnz': {
      'en':
          'A quantum computer came up with better answers to a physics problem than a conventional supercomputer.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '000j3c05': {
      'en': 'Research team simulates super diffusion on a quantum computer',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '6r3n8uv7': {
      'en':
          'Trinity\'s quantum physicists in collaboration with IBM Dublin have successfully simulated super diffusion in a system of interacting quantum particles on a quantum computer.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'siyug5kc': {
      'en': 'All',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '7as7t7ve': {
      'en': 'Quantum Computing Advance Begins New Era, IBM Says',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '120asenx': {
      'en':
          'A quantum computer came up with better answers to a physics problem than a conventional supercomputer.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '7w6lgujo': {
      'en': 'Research team simulates super diffusion on a quantum computer',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'jdpt03yf': {
      'en':
          'Trinity\'s quantum physicists in collaboration with IBM Dublin have successfully simulated super diffusion in a system of interacting quantum particles on a quantum computer.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'iwytw5qn': {
      'en': 'Dashboard',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '2q83lbot': {
      'en': '__',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // Profile
  {
    'zw93saos': {
      'en': 'My Profile',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'dxuj43rf': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'zn98tb0y': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'ron6zjju': {
      'en': 'Reset My Password',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'oeri7ios': {
      'en': 'Save Changes',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '7lnyiaou': {
      'en': 'Dashboard',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '603qnw43': {
      'en': '__',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // paymentBilling
  {
    '3hi15q84': {
      'en': 'Payment & Billing',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'n5wrcw87': {
      'en': 'Transaction History',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'zdc3ihma': {
      'en': 'Cancel Subscription',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '8600fesb': {
      'en': 'Paid On',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'oovam4oe': {
      'en': 'Plan',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '8wfby7ly': {
      'en': 'Amount',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'mafjyh5n': {
      'en': 'Jan. 30, 2023',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'nch1krwt': {
      'en': 'Starter',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'a2ybrcc2': {
      'en': '\$49.00',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'laxq4fmk': {
      'en': 'Jan. 30, 2023',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'cgsluf37': {
      'en': 'Starter',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'wyg6ai7k': {
      'en': '\$49.00',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'xq4dagm9': {
      'en': 'Jan. 30, 2023',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '5k76pux3': {
      'en': 'Starter',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'zhys4vil': {
      'en': '\$49.00',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'wag8r82q': {
      'en': 'Dashboard',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '43en6scv': {
      'en': '__',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // modal_success
  {
    've9hthti': {
      'en': 'Send Contract Confirmation',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'uynrbx1l': {
      'en': 'A new contract has been generated for:',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '41dlan5y': {
      'en': 'Randy Alcorn',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'mkel31qk': {
      'en': 'Head of Procurement',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '482rp5f1': {
      'en': 'ACME Co.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'gx1qogks': {
      'en': 'Next Steps',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'zwx7ozxj': {
      'en':
          'Send the information below. And we will send an email with details to the customer and allow you to manage it in your dashboard.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'r6ob1hwl': {
      'en': 'Send Information',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '6y1ap632': {
      'en': 'Never Mind',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // modal_Message
  {
    'hv70ugb5': {
      'en': 'Congratulations!',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'lmvgqhrc': {
      'en':
          'Now that a contract has been generated for this customer please contact them with the date you will send the signed agreement.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '5x5pbgtg': {
      'en': 'Okay',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'sle1nfod': {
      'en': 'Continue',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // modal_Welcome
  {
    'ik75pamy': {
      'en': 'Congratulations!',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'ltzbx0rg': {
      'en': 'A new contract has been generated for:',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '2q3lnnv7': {
      'en': 'Continue',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // webNav
  {
    'e7gkimju': {
      'en': 'Dashboard',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'rsaxk3l7': {
      'en': 'Articles',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'obc2ycrz': {
      'en': 'Profile',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'yyk7x4xu': {
      'en': 'Log Out',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // commandPalette
  {
    'kehnhttn': {
      'en': 'Search platform...',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '5xluzh5j': {
      'en': 'Search',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '3ugmqxwv': {
      'en': 'Quick Links',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'efvw3btx': {
      'en': 'Find Contract',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'g7t8q44b': {
      'en': 'Find Customer',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'tbn06rpz': {
      'en': 'New Contract',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'y6x6puak': {
      'en': 'New Customer',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '887jkpbv': {
      'en': 'Recent Searches',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'zq78z6kk': {
      'en': 'Newport Financ',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'fmrgo7ad': {
      'en': 'Harry Styles',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // editProfilePhoto
  {
    'wpvip9bw': {
      'en': 'Change Photo',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'hxt6l4cl': {
      'en':
          'Upload a new photo below in order to change your avatar seen by others.',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '9ifbx8ng': {
      'en': 'Upload Image',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'jvosirvq': {
      'en': 'Save Changes',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // setKeywords
  {
    'lqb0wo77': {
      'en': 'Set Up Your Account',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'mar8jzia': {
      'en': 'First Name',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'f02maexh': {
      'en': 'Last Name',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'ofcpvav1': {
      'en': 'Phone ',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'i3vknhze': {
      'en':
          'Which keyword should we use for relevant research journal searches?\"',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '111ls6oa': {
      'en': 'Keywords',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'liybcxhd': {
      'en': 'Get Article Updates',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
  // Miscellaneous
  {
    'jrn34q57': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'zq5m990c': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '65e2tfs2': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'ddazihx4': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'db03cpjj': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'fdb9078p': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '80ouzj9q': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '6rzhptp9': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'ce8c4ty0': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'rwsbo2gj': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'adhsc8p7': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'kcvqa08x': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'dqrzd6sq': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'dpqtohyf': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'v01vf71s': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'gcv6def1': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'um9es99m': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'o4enbz4j': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '8z4tvfh7': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '2ybzla8x': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'd1wdf5i1': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '4iuf0dd0': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    '2py80kgi': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'p6lsrh2a': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
    'ne8cclp9': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'hi': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
